site_name: onshape-robotics-toolkit
repo_url: https://github.com/neurobionics/onshape-robotics-toolkit
site_url: https://neurobionics.github.io/onshape-robotics-toolkit
site_description: A python library to facilitate interaction with Onshape's REST API
site_author: Senthur Ayyappan
edit_uri: edit/main/docs/
repo_name: neurobionics/onshape-robotics-toolkit
copyright: Maintained by <a href="https://neurobionics.com">Senthur Ayyappan</a>.

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Developing: developing.md
  - Contributing: contributing.md
  - Tutorials:
      - Exporting to URDF: tutorials/export.md
      - Editing a CAD assembly: tutorials/edit.md
  - API Documentation:
      - Models:
          - Assembly: api/assembly.md
          - Document: api/document.md
          - Element: api/element.md
          - Geometry: api/geometry.md
          - Joint: api/joint.md
          - Link: api/link.md
          - Mass: api/mass.md
          - Variable: api/variable.md
      - Connect: api/connect.md
      - Graph: api/graph.md
      - Log: api/log.md
      - Mesh: api/mesh.md
      - Parse: api/parse.md
      - Robot: api/robot.md
      - Urdf: api/urdf.md
      - Utilities: api/utilities.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - python
    - yaml
    - bash
    - json
    - markdown
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/neurobionics/onshape-robotics-toolkit
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/onshape-robotics-toolkit

markdown_extensions:
  - attr_list
  - pymdownx.snippets
  - pymdownx.highlight # For syntax highlighting
  - pymdownx.superfences

  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
